
import { GoogleGenAI } from "@google/genai";
import { GenerationOptions } from "../types";

export const generateImage = async (
  prompt: string,
  options: GenerationOptions
): Promise<{ url: string; modelUsed: string }> => {
  const modelName = options.highQuality ? 'gemini-3-pro-image-preview' : 'gemini-2.5-flash-image';
  
  // For high quality Pro model, ensure key is selected via prompt flow
  if (options.highQuality) {
    const hasKey = await window.aistudio.hasSelectedApiKey();
    if (!hasKey) {
      await window.aistudio.openSelectKey();
      // Proceed assuming success as per guidelines to avoid race condition
    }
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: options.aspectRatio,
          ...(options.highQuality && options.imageSize ? { imageSize: options.imageSize } : {}),
        },
      },
    });

    let imageUrl = '';
    
    // Iterate through parts to find the image part
    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return {
      url: imageUrl,
      modelUsed: modelName
    };
  } catch (error: any) {
    // If Pro model fails with "entity not found", user might need to re-select key
    if (error?.message?.includes("Requested entity was not found") && options.highQuality) {
      await window.aistudio.openSelectKey();
    }
    throw error;
  }
};
